"""add camera, video, analysis tables

Revision ID: 2e04790b7255
Revises: 9a0f43bc33e7
Create Date: 2026-09-07 18:29:21.387886

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e04790b7255"
down_revision: str | Sequence[str] | None = "9a0f43bc33e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "d_camera",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("camera_id", sa.String(), nullable=False, comment="Номер камеры"),
        sa.Column(
            "camera_class_cd",
            sa.Integer(),
            nullable=True,
            comment="Идентификатор класса камеры",
        ),
        sa.Column("camera_class", sa.String(), nullable=True, comment="Класс камеры"),
        sa.Column("model", sa.String(), nullable=True, comment="Модель"),
        sa.Column(
            "camera_name", sa.String(), nullable=False, comment="Название камеры"
        ),
        sa.Column("camera_place", sa.String(), nullable=True, comment="Адрес"),
        sa.Column(
            "camera_place_cd",
            sa.Integer(),
            nullable=True,
            comment="Идентификатор адреса",
        ),
        sa.Column(
            "serial_number", sa.String(), nullable=True, comment="Серийный номер"
        ),
        sa.Column(
            "camera_type_cd",
            sa.Integer(),
            nullable=True,
            comment="Идентификатор типа камеры",
        ),
        sa.Column("camera_type", sa.String(), nullable=True, comment="Тип камеры"),
        sa.Column("camera_latitude", sa.Float(), nullable=False, comment="Широта"),
        sa.Column("camera_longitude", sa.Float(), nullable=False, comment="Долгота"),
        sa.Column(
            "archive", sa.Boolean(), nullable=False, comment="Признак архивной записи"
        ),
        sa.Column("azimuth", sa.Integer(), nullable=True, comment="Азимут"),
        sa.Column(
            "process_dttm",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_d_camera_camera_id"), "d_camera", ["camera_id"], unique=True
    )
    op.create_index(
        op.f("ix_d_camera_camera_name"), "d_camera", ["camera_name"], unique=False
    )
    op.create_table(
        "videos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "name",
            sa.String(),
            nullable=False,
            comment="Наименование видео (содержит id видео)",
        ),
        sa.Column("camera_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column(
            "duration_seconds",
            sa.Integer(),
            nullable=True,
            comment="Длительность видео, сек",
        ),
        sa.Column("resolution_width", sa.Integer(), nullable=True),
        sa.Column("resolution_height", sa.Integer(), nullable=True),
        sa.Column("fps", sa.Integer(), nullable=True),
        sa.Column(
            "time_of_day",
            sa.Enum("MORNING", "DAY", "EVENING", "NIGHT", name="time_of_day"),
            nullable=True,
        ),
        sa.Column(
            "tracing_status",
            sa.Enum("DONE", "RUN", "ERROR", name="tracing_status"),
            nullable=False,
        ),
        sa.Column(
            "file_key", sa.String(), nullable=False, comment="Ключ видеофайла в MinIO"
        ),
        sa.Column(
            "first_frame_key",
            sa.String(),
            nullable=True,
            comment="Ключ первого кадра в MinIO",
        ),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["d_camera.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_videos_author_id"), "videos", ["author_id"], unique=False)
    op.create_index(op.f("ix_videos_camera_id"), "videos", ["camera_id"], unique=False)
    op.create_index(
        op.f("ix_videos_uploaded_at"), "videos", ["uploaded_at"], unique=False
    )
    op.create_table(
        "analyses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("video_id", sa.UUID(), nullable=False),
        sa.Column(
            "analysis_type",
            sa.Enum("TRAFFIC", "SPEED", name="analysis_type"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("DONE", "RUN", "ERROR", name="analysis_status"),
            nullable=False,
        ),
        sa.Column("result", sa.JSON(), nullable=True, comment="Результат обработки"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analyses_video_id"), "analyses", ["video_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analyses_video_id"), table_name="analyses")
    op.drop_table("analyses")
    op.drop_index(op.f("ix_videos_uploaded_at"), table_name="videos")
    op.drop_index(op.f("ix_videos_camera_id"), table_name="videos")
    op.drop_index(op.f("ix_videos_author_id"), table_name="videos")
    op.drop_table("videos")
    op.drop_index(op.f("ix_d_camera_camera_name"), table_name="d_camera")
    op.drop_index(op.f("ix_d_camera_camera_id"), table_name="d_camera")
    op.drop_table("d_camera")
    # ### end Alembic commands ###
